kind: pipeline
type: kubernetes
name: default

steps:
  # --- 新增步骤：手动切换到指定 Tag ---
- name: checkout-tag
  image: registry.cn-shenzhen.aliyuncs.com/dolphindong/git:v2.52.0
  commands:
    # 1. 判断是否在页面上输了 Tag
    - if [ -z "$BUILD_TAG" ]; then echo "No tag provided, using default commit"; exit 0; fi

    # 2. 如果输了 Tag，强制 Fetch 所有 tag 并切换
    - echo "Manual build tag detected:$BUILD_TAG"
    - git fetch --tags
    - git checkout $BUILD_TAG
    - echo "Switched to tag: $(git describe --tags)"
- name: build binary
  image: golang:1.25.5
  service_account_name: drone
  volumes:
    - name: cache
      path: /go
      sub_path: go/drone-ci-demo
    - name: binary
      path: /tmp/drone-ci-demo
  commands:
  - go env -w GOPROXY="https://goproxy.cn,direct"
  - go mod tidy
  - go build -o drone-ci-demo main.go
  - chmod +x drone-ci-demo
  - ls -lh drone-ci-demo

- name: build-image
  image: gcr.io/kaniko-project/executor:debug
  volumes:
    - name: docker-config
      path: /kaniko/.docker                 # 这里挂载阿里云登录的 config.json
  commands:
    - |
      if [  -n "$BUILD_TAG" ] ; # 优先使用tag
      then
        export IMAGE_TAG='${BUILD_TAG}'
      else
        export IMAGE_TAG='${CI_COMMIT_BRANCH}_${DRONE_COMMIT_SHA:0:9}'
      fi
    - >
      /kaniko/executor
      --dockerfile=Dockerfile
      --context=/drone/src
      --destination=registry.cn-shenzhen.aliyuncs.com/dolphindong/drone-ci-demo:${IMAGE_TAG}


#- name: build image
volumes:
  - name: cache
    claim:
      name: drone-build-cache
      read_only: false # <true|false>
  - name: docker-config
    secret:
      name: docker-config
