kind: pipeline
type: kubernetes
name: default

#trigger:
#  event:
#    - push
#    - tag        # 允许 tag 事件触发
#    - custom
steps:
- name: build binary
  image: golang:1.25.5
  service_account_name: drone
  volumes:
    - name: cache
      path: /go
      sub_path: go/drone-ci-demo
    - name: binary
      path: /tmp/drone-ci-demo
  commands:
    - go env -w GOPROXY="https://goproxy.cn,direct"
    - go mod tidy
    - |
      export VERSION="${DRONE_TAG:-${DRONE_COMMIT_BRANCH}}"
      export COMMIT="${DRONE_COMMIT_SHA:0:9}"
      export BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
      go build -ldflags "-X 'main.Version=$VERSION' -X 'main.GitCommit=$COMMIT' -X 'main.BuildTime=$BUILD_TIME'" -o drone-ci-demo main.go
    - chmod +x drone-ci-demo
    - ls -lh drone-ci-demo

- name: build-image
  image: gcr.io/kaniko-project/executor:debug
  volumes:
    - name: docker-config
      path: /kaniko/.docker                 # 这里挂载阿里云登录的 config.json
  commands:
    - echo "DRONE_TAG=$DRONE_TAG"
    - |
      if [ -n "$DRONE_TAG" ]; then
       IMAGE_TAG="$DRONE_TAG"
      else
       IMAGE_TAG="${DRONE_COMMIT_BRANCH}_${DRONE_COMMIT_SHA:0:9}"
      fi
    - >
      /kaniko/executor
      --dockerfile=Dockerfile
      --context=/drone/src
      --destination=registry.cn-shenzhen.aliyuncs.com/dolphindong/drone-ci-demo:$IMAGE_TAG

#- name: build image
volumes:
  - name: cache
    claim:
      name: drone-build-cache
      read_only: false # <true|false>
  - name: docker-config
    secret:
      name: docker-config
